name: Deploy GitHub Pages

on: workflow_call

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TENABLE_LINKING_KEY: ${{ secrets.TENABLE_LINKING_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Update (download and check) installer script
        run: make update

      - name: Build installer script
        run: make build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
