name: Deploy

on: workflow_call

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TENABLE_LINKING_KEY: ${{ secrets.TENABLE_LINKING_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Update functions.sh with latest tag
        run: |
          LATEST_TAG=${{ github.ref_name }}
          sed -i "s/^CER_NESSUS_VERSION=.*/CER_NESSUS_VERSION=$LATEST_TAG/" scripts/functions.sh

      - name: Verify installer script
        run: make verify

      - name: Build installer script
        run: make build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
