---
name: Lint all

on: workflow_call

jobs:
  lint_all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: make lint
