---
name: Lint all

on: workflow_call

jobs:
  lint_all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            ./dist
            ./src/install_agent*
